### ISSUE TITLE
NSMakeRange error in Version 6.2 (6C131e)

### ISSUE THREAD

**Issue by boolAeon** [ayanonagon/talks#3]
I had to change NSMakeRange(0, count(text)) to NSMakeRange(0, (text as NSString).length) to fix "String is not convertible to Range<i>" error with the above version of Xcode

**Comment by kylef** [comment]
I think using `countElements` is slightly cleaner than using Foundation types:

``` swift
NSMakeRange(0, countElements(text))
```

Note, in Xcode 6.3, it was changed to `count`.

**Comment by ayanonagon** [comment]
Ah, during the talk I gave a warning that this was written for Swift 1.2, but it’s not very clear in the playground file itself, so I’ll add a note. Thanks for pointing that out! :octocat:
